
services:
  recipe:
      container_name: wallet-rest-api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '8080:8080'
      environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db_pg:5432/wallets
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: root
      depends_on:
        - db_pg

  db_pg:
      image: postgres
      environment:
        POSTGRES_DB: wallets
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      ports:
        - '5432:5432'
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql



